[package]
name = "reddit_motion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For localization
fluent-templates = "0.8.0"
lazy_static = "1.4.0"
unic-langid = "0.9.1"