[package]
name = "reddit-motion"
version = "0.1.0"
edition = "2021"

[dependencies]
# For downloading neccessary youtube videos
rustube = "0.6.0"

#colored = "2.0.4" # For better terminal reporting
# For parsing settings.toml
#serde = { version = "1.0.145" , features = ["derive"] }
#toml = "0.7.6"

#roux = "2.2.9" # For accessing reddit