[package]
name = "reddit-motion"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[workspace]
members = ["reddit-motion-core", "reddit-motion-impl"]

[workspace.package]
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["Aarav Shah <aaravaditya51@gmail.com>"]
description = "Transform Reddit Posts and Custom Text into Engaging Videos with Localization. Customize Content, Boost Speed, Share on Social Media – Experience its Excellence!"
documentation = "https://docs.rs/reddit-motion"
repository = "https://github.com/Deaths-Door/reddit-motion"
homepage = "https://github.com/Deaths-Door/reddit-motion"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
reddit-motion-core = { path = "../reddit-motion/reddit-motion-core" }
serde = { version = "1.0.145" , features = ["derive"] }
unic-langid = "0.9.4"
tokio = { version = "1.35.1" } 
thiserror = "1.0.47"

[workspace.lints.clippy]
correctness = "deny"
suspicious = "deny"
complexity = "deny"
perf = "deny"
style = "deny"
cargo = "deny"

[workspace.lints.rust]
missing_docs= "deny"
missing_debug_implementations= "deny"
unsafe_code= "deny"
unused_mut= "deny"
unused_allocation= "deny"
unused_must_use= "deny"
unreachable_patterns= "deny"
unstable_features= "deny"
unsafe_op_in_unsafe_fn= "deny"
trivial_casts= "deny"
overflowing_literals= "deny"
non_snake_case= "deny"

[dependencies]
reddit-motion-impl = { path = "../reddit-motion/reddit-motion-impl" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }